// Pure HTTP/SOCKS proxy list sources ONLY.
// DO NOT add V2ray, Xray, Hysteria, Trojan, VLESS, VMess subscription/config URLs here.
// Those are VPN relay configs, not HTTP/SOCKS proxies.

export const SOURCES = [
  // === TheSpeedX (high quality, large lists) ===
  "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt",
  "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt",
  "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt",
  "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
  "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",

  // === ProxyScraper ===
  "https://raw.githubusercontent.com/ProxyScraper/ProxyScraper/main/http.txt",
  "https://raw.githubusercontent.com/ProxyScraper/ProxyScraper/main/socks4.txt",
  "https://raw.githubusercontent.com/ProxyScraper/ProxyScraper/main/socks5.txt",
  "https://raw.githubusercontent.com/ProxyScraper/ProxyScraper/refs/heads/main/http.txt",
  "https://raw.githubusercontent.com/ProxyScraper/ProxyScraper/refs/heads/main/socks4.txt",
  "https://raw.githubusercontent.com/ProxyScraper/ProxyScraper/refs/heads/main/socks5.txt",

  // === fyvri fresh-proxy-list ===
  "https://raw.githubusercontent.com/fyvri/fresh-proxy-list/archive/storage/classic/all.txt",
  "https://raw.githubusercontent.com/fyvri/fresh-proxy-list/archive/storage/classic/http.txt",
  "https://raw.githubusercontent.com/fyvri/fresh-proxy-list/archive/storage/classic/socks4.txt",
  "https://raw.githubusercontent.com/fyvri/fresh-proxy-list/archive/storage/classic/socks5.txt",

  // === dpangestuw ===
  "https://raw.githubusercontent.com/dpangestuw/Free-Proxy/refs/heads/main/All_proxies.txt",
  "https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/http_proxies.txt",
  "https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/socks4_proxies.txt",
  "https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/socks5_proxies.txt",

  // === Other curated proxy lists ===
  "https://raw.githubusercontent.com/thenasty1337/free-proxy-list/main/data/latest/proxies.txt",
  "https://raw.githubusercontent.com/theriturajps/proxy-list/main/proxies.txt",
  "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
  "https://raw.githubusercontent.com/officialputuid/ProxyForEveryone/refs/heads/main/xResults/Proxies.txt",
  "https://raw.githubusercontent.com/monosans/proxy-list/refs/heads/main/proxies/all.txt",
  "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/all.txt",
  "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/all.txt",
  "https://raw.githubusercontent.com/iplocate/free-proxy-list/refs/heads/main/all-proxies.txt",
  "https://raw.githubusercontent.com/prxchk/proxy-list/refs/heads/main/all.txt",
  "https://raw.githubusercontent.com/elliottophellia/proxylist/master/results/pmix_checked.txt",
  "https://raw.githubusercontent.com/trio666/proxy-checker/refs/heads/main/all.txt",
  "https://raw.githubusercontent.com/LoneKingCode/free-proxy-db/refs/heads/main/proxies/all.txt",

  // === proxifly ===
  "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/http/data.txt",
  "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/https/data.txt",
  "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/socks4/data.txt",
  "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/socks5/data.txt",

  // === HTTP specific ===
  "https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt",
  "https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt",
  "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt",
  "https://raw.githubusercontent.com/gitrecon1455/fresh-proxy-list/refs/heads/main/proxylist.txt",
  "https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt",
  "https://raw.githubusercontent.com/KUTlime/ProxyList/main/ProxyList.txt",
  "https://raw.githubusercontent.com/mmpx12/proxy-list/master/proxies.txt",
  "https://raw.githubusercontent.com/MrMarble/proxy-list/main/all.txt",
  "https://raw.githubusercontent.com/noarche/proxylist-socks5-sock4-exported-updates/main/http-online.txt",
  "https://raw.githubusercontent.com/officialputuid/KangProxy/refs/heads/KangProxy/http/http.txt",
  "https://raw.githubusercontent.com/r00tee/Proxy-List/main/Https.txt",
  "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
  "https://raw.githubusercontent.com/SevenworksDev/proxy-list/main/proxies/http.txt",
  "https://raw.githubusercontent.com/SevenworksDev/proxy-list/main/proxies/unknown.txt",
  "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt",
  "https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data.txt",
  "https://raw.githubusercontent.com/Tsprnay/Proxy-lists/master/proxies/http.txt",
  "https://raw.githubusercontent.com/TuanMinPay/live-proxy/master/http.txt",
  "https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/http.txt",
  "https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/http.txt",
  "https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt",
  "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt",
  "https://raw.githubusercontent.com/dinoz0rg/proxy-list/main/scraped_proxies/http.txt",
  "https://raw.githubusercontent.com/zebbern/Proxy-Scraper/main/http.txt",
  "https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/unchecked.txt",
  "https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/http.txt",
  "https://raw.githubusercontent.com/javadbazokar/PROXY-List/main/http.txt",
  "https://raw.githubusercontent.com/vmheaven/VMHeaven-Free-Proxy-Updated/main/http.txt",
  "https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/refs/heads/main/free.txt",
  "https://raw.githubusercontent.com/FifzzSENZE/Master-Proxy/master/proxies/http.txt",
  "https://github.com/handeveloper1/Proxy/raw/refs/heads/main/Proxies-Ercin/http.txt",
  "https://raw.githubusercontent.com/fahimscirex/proxybd/refs/heads/master/proxylist/http.txt",
  "https://github.com/Anonym0usWork1221/Free-Proxies/raw/refs/heads/main/proxy_files/http_proxies.txt",
  "https://github.com/zenjahid/FreeProxy4u/raw/refs/heads/main/http.txt",
  "https://raw.githubusercontent.com/casals-ar/proxy-list/refs/heads/main/http",
  "https://raw.githubusercontent.com/BreakingTechFr/Proxy_Free/refs/heads/main/proxies/http.txt",
  "https://raw.githubusercontent.com/VolkanSah/Auto-Proxy-Fetcher/refs/heads/main/proxies.txt",
  "https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/refs/heads/master/proxy_list.txt",
  "https://raw.githubusercontent.com/databay-labs/free-proxy-list/refs/heads/master/http.txt",
  "https://raw.githubusercontent.com/variableninja/proxyscraper/refs/heads/main/proxies/http.txt",
  "https://raw.githubusercontent.com/berkay-digital/Proxy-Scraper/refs/heads/main/proxies.txt",
  "https://raw.githubusercontent.com/iniridwanul/Hoot/refs/heads/master/proxylist/http.txt",
  "https://raw.githubusercontent.com/iniridwanul/Hoot/refs/heads/master/anonymous-proxylist/http.txt",
  "https://github.com/XigmaDev/proxy/raw/refs/heads/main/proxies.txt",
  "https://github.com/chekamarue/proxies/raw/refs/heads/main/https.txt",
  "https://github.com/chekamarue/proxies/raw/refs/heads/main/httpss.txt",
  "https://github.com/claude89757/free_https_proxies/raw/refs/heads/main/https_proxies.txt",
  "https://github.com/claude89757/free_https_proxies/raw/refs/heads/main/isz_https_proxies.txt",
  "https://raw.githubusercontent.com/joy-deploy/free-proxy-list/refs/heads/main/data/latest/types/http/proxies.txt",
  "https://github.com/andigwandi/free-proxy/raw/refs/heads/main/proxy_list.txt",
  "https://github.com/murtaja89/public-proxies/raw/refs/heads/main/proxies_all.txt",
  "https://raw.githubusercontent.com/parserpp/ip_ports/refs/heads/main/proxyinfo.txt",
  "https://raw.githubusercontent.com/Vadim287/free-proxy/refs/heads/main/proxies/http.txt",
  "https://raw.githubusercontent.com/Firmfox/Proxify/refs/heads/main/proxies/http.txt",
  "https://raw.githubusercontent.com/ebrasha/abdal-proxy-hub/refs/heads/main/http-proxy-list-by-EbraSha.txt",
  "https://rootjazz.com/proxies/proxies.txt",
  "https://proxyspace.pro/http.txt",
  "https://raw.githubusercontent.com/casa-ls/proxy-list/refs/heads/main/http",
  "https://raw.githubusercontent.com/jetkai/proxy-list/refs/heads/main/online-proxies/txt/proxies-http.txt",
  "https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt",

  // === HTTPS specific ===
  "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt",
  "https://raw.githubusercontent.com/im-razvan/proxy_list/main/https.txt",
  "https://raw.githubusercontent.com/noarche/proxylist-socks5-sock4-exported-updates/main/connect-online.txt",
  "https://raw.githubusercontent.com/officialputuid/KangProxy/refs/heads/KangProxy/https/https.txt",
  "https://raw.githubusercontent.com/SevenworksDev/proxy-list/main/proxies/https.txt",
  "https://raw.githubusercontent.com/Tsprnay/Proxy-lists/master/proxies/https.txt",
  "https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/https.txt",
  "https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/https.txt",
  "https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt",
  "https://raw.githubusercontent.com/zebbern/Proxy-Scraper/main/https.txt",
  "https://raw.githubusercontent.com/javadbazokar/PROXY-List/main/https.txt",
  "https://raw.githubusercontent.com/vmheaven/VMHeaven-Free-Proxy-Updated/main/https.txt",
  "https://raw.githubusercontent.com/FifzzSENZE/Master-Proxy/master/proxies/https.txt",
  "https://github.com/handeveloper1/Proxy/raw/refs/heads/main/Proxies-Ercin/https.txt",
  "https://github.com/Anonym0usWork1221/Free-Proxies/raw/refs/heads/main/proxy_files/https_proxies.txt",
  "https://raw.githubusercontent.com/databay-labs/free-proxy-list/refs/heads/master/https.txt",
  "https://github.com/dinoz0rg/proxy-list/raw/refs/heads/main/scraped_proxies/http.txt",
  "https://raw.githubusercontent.com/Firmfox/Proxify/refs/heads/main/proxies/https.txt",
  "https://raw.githubusercontent.com/ebrasha/abdal-proxy-hub/refs/heads/main/https-proxy-list-by-EbraSha.txt",
  "https://raw.githubusercontent.com/jetkai/proxy-list/refs/heads/main/online-proxies/txt/proxies-https.txt",

  // === SOCKS4 specific ===
  "https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks4.txt",
  "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
  "https://raw.githubusercontent.com/noarche/proxylist-socks5-sock4-exported-updates/main/socks4-online.txt",
  "https://raw.githubusercontent.com/officialputuid/KangProxy/refs/heads/KangProxy/sock4/socks4.txt",
  "https://raw.githubusercontent.com/r00tee/Proxy-List/main/Socks4.txt",
  "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
  "https://raw.githubusercontent.com/SevenworksDev/proxy-list/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/Tsprnay/Proxy-lists/master/proxies/socks4.txt",
  "https://raw.githubusercontent.com/TuanMinPay/live-proxy/master/socks4.txt",
  "https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/socks4.txt",
  "https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks4.txt",
  "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks4.txt",
  "https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt",
  "https://raw.githubusercontent.com/dinoz0rg/proxy-list/main/scraped_proxies/socks4.txt",
  "https://raw.githubusercontent.com/zebbern/Proxy-Scraper/main/socks4.txt",
  "https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/vmheaven/VMHeaven-Free-Proxy-Updated/main/socks4.txt",
  "https://raw.githubusercontent.com/FifzzSENZE/Master-Proxy/master/proxies/socks4.txt",
  "https://github.com/handeveloper1/Proxy/raw/refs/heads/main/Proxies-Ercin/socks4.txt",
  "https://raw.githubusercontent.com/fahimscirex/proxybd/refs/heads/master/proxylist/socks4.txt",
  "https://github.com/Anonym0usWork1221/Free-Proxies/raw/refs/heads/main/proxy_files/socks4_proxies.txt",
  "https://github.com/zenjahid/FreeProxy4u/raw/refs/heads/main/socks4.txt",
  "https://raw.githubusercontent.com/casals-ar/proxy-list/refs/heads/main/socks4",
  "https://raw.githubusercontent.com/BreakingTechFr/Proxy_Free/refs/heads/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/variableninja/proxyscraper/refs/heads/main/proxies/socks.txt",
  "https://raw.githubusercontent.com/iniridwanul/Hoot/refs/heads/master/proxylist/socks4.txt",
  "https://raw.githubusercontent.com/iniridwanul/Hoot/refs/heads/master/anonymous-proxylist/socks4.txt",
  "https://raw.githubusercontent.com/joy-deploy/free-proxy-list/refs/heads/main/data/latest/types/socks4/proxies.txt",
  "https://raw.githubusercontent.com/Vadim287/free-proxy/refs/heads/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/Firmfox/Proxify/refs/heads/main/proxies/socks4.txt",
  "https://raw.githubusercontent.com/ebrasha/abdal-proxy-hub/refs/heads/main/socks4-proxy-list-by-EbraSha.txt",
  "https://raw.githubusercontent.com/casa-ls/proxy-list/refs/heads/main/socks4",
  "https://raw.githubusercontent.com/jetkai/proxy-list/refs/heads/main/online-proxies/txt/proxies-socks4.txt",
  "https://raw.githubusercontent.com/ArteffKod/socks4/main/socks4%20proxy",

  // === SOCKS5 specific ===
  "https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks5.txt",
  "https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/im-razvan/proxy_list/main/socks5.txt",
  "https://raw.githubusercontent.com/noarche/proxylist-socks5-sock4-exported-updates/main/socks5-online.txt",
  "https://raw.githubusercontent.com/officialputuid/KangProxy/refs/heads/KangProxy/socks5/socks5.txt",
  "https://raw.githubusercontent.com/r00tee/Proxy-List/main/Socks5.txt",
  "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
  "https://raw.githubusercontent.com/SevenworksDev/proxy-list/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/Tsprnay/Proxy-lists/master/proxies/socks5.txt",
  "https://raw.githubusercontent.com/TuanMinPay/live-proxy/master/socks5.txt",
  "https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/socks5.txt",
  "https://raw.githubusercontent.com/Vann-Dev/proxy-list/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks5.txt",
  "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks5.txt",
  "https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt",
  "https://raw.githubusercontent.com/dinoz0rg/proxy-list/main/scraped_proxies/socks5.txt",
  "https://raw.githubusercontent.com/zebbern/Proxy-Scraper/main/socks5.txt",
  "https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/vmheaven/VMHeaven-Free-Proxy-Updated/main/socks5.txt",
  "https://raw.githubusercontent.com/FifzzSENZE/Master-Proxy/master/proxies/socks5.txt",
  "https://github.com/handeveloper1/Proxy/raw/refs/heads/main/Proxies-Ercin/socks5.txt",
  "https://github.com/Anonym0usWork1221/Free-Proxies/raw/refs/heads/main/proxy_files/socks5_proxies.txt",
  "https://github.com/zenjahid/FreeProxy4u/raw/refs/heads/main/socks5.txt",
  "https://raw.githubusercontent.com/casals-ar/proxy-list/refs/heads/main/socks5",
  "https://raw.githubusercontent.com/BreakingTechFr/Proxy_Free/refs/heads/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/databay-labs/free-proxy-list/refs/heads/master/socks5.txt",
  "https://raw.githubusercontent.com/iniridwanul/Hoot/refs/heads/master/proxylist/socks5.txt",
  "https://raw.githubusercontent.com/iniridwanul/Hoot/refs/heads/master/anonymous-proxylist/socks5.txt",
  "https://raw.githubusercontent.com/joy-deploy/free-proxy-list/refs/heads/main/data/latest/types/socks5/proxies.txt",
  "https://raw.githubusercontent.com/Vadim287/free-proxy/refs/heads/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/Firmfox/Proxify/refs/heads/main/proxies/socks5.txt",
  "https://raw.githubusercontent.com/ebrasha/abdal-proxy-hub/refs/heads/main/socks5-proxy-list-by-EbraSha.txt",
  "https://raw.githubusercontent.com/casa-ls/proxy-list/refs/heads/main/socks5",
  "https://raw.githubusercontent.com/jetkai/proxy-list/refs/heads/main/online-proxies/txt/proxies-socks5.txt",

  // === zloi-user hideip.me ===
  "https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/main/socks5.txt",
  "https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/main/socks4.txt",
  "https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/main/https.txt",
  "https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/main/http.txt",
  "https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/main/connect.txt",

  // === API endpoints ===
  "https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&proxy_format=protocolipport&format=text",
  "https://api.proxyscrape.com/v3/free-proxy-list/get?request=displayproxies&protocol=http&proxy_format=ipport&format=text&timeout=20000",
  "https://sockslist.us/Raw",
];